#!/bin/sh

COMMAND=$1

# Start command
if [ "$COMMAND" == "start" ]; then
  echo "Starting uhc..."
  echo "RUNNING" > ./STATUS
  # Execute command and use GNU screen to keep the server running
    screen -dmS uhc ./scripts/loop.sh
fi

# Stop command
if [ "$COMMAND" == "stop" ]; then
  echo "Stopping uhc..."
  echo "STOPPING" > ./STATUS
  screen -S uhc -X stuff "stop$(printf \\r)"
  echo "STOPPED" > ./STATUS
fi

# Restart command
if [ "$COMMAND" == "restart" ]; then
  echo "Restarting uhc..."
  screen -t uhc -X stuff "stop$(printf \\r)"
  sleep 5
  screen -dmS uhc ./scripts/start.sh
fi

# Console command
if [ "$COMMAND" == "console" ]; then
  echo "Opening console..."
  screen -r uhc
fi

# Update command
if [ "$COMMAND" == "update" ]; then
  echo "Updating uhc..."
  ./scripts/update.sh
fi

# Force kill command
if [ "$COMMAND" == "forcekill" ]; then
  echo "Force killing uhc..."
  killall -9 java
  killall -9 screen
fi

# Upload log
if [ "$COMMAND" == "log" ]; then
  echo "Uploading log..."
  cat ./logs/latest.log | nc termbin.com 9999
fi

# Mode command
if [ "$COMMAND" == "mode" ]; then
    MODE=$2
    echo "Setting mode to $MODE..."
    FILE_PATH="./plugins/UhcCore/config.$MODE.yml"
    MODE_DATA=$(cat $FILE_PATH)

    if([ -z "$MODE_DATA" ]); then
        echo "\nMode $MODE does not exist"
        echo "Available modes:"
        ls ./plugins/UhcCore/config.*.yml | xargs -n 1 basename | sed 's/config.//g' | sed 's/.yml//g'
        exit 1
    fi

    echo "Updating config.yml..."
    echo "$MODE_DATA" > ./plugins/UhcCore/config.yml
    echo "Updated config.yml"
fi
