#!/bin/bash

COMMAND=$1

# Start command
if [ "$COMMAND" == "start" ]; then
  echo "Starting uhc..."
  echo "RUNNING" > ./STATUS
  # Execute command and use GNU screen to keep the server running
    screen -dmS uhc ./scripts/loop.sh
fi

# Stop command
if [ "$COMMAND" == "stop" ]; then
  echo "Stopping uhc..."
  echo "STOPPING" > ./STATUS
  screen -S uhc -X stuff "$(printf \\r)stop$(printf \\r)"
  echo "STOPPED" > ./STATUS
fi

# Restart command
if [ "$COMMAND" == "restart" ]; then
  echo "Restarting uhc..."
  echo
  echo "STOPPING" > ./STATUS
  screen -t uhc -X stuff "$(printf \\r)stop$(printf \\r)"
  echo "Server stop initiated"
  sleep 15
  echo "Server is probably stopped... starting again"
  echo "RUNNING" > ./STATUS
  screen -dmS uhc ./scripts/loop.sh
fi

# Console command
if [ "$COMMAND" == "console" ]; then
  echo "Opening console..."
  screen -r uhc
fi

# Update command
if [ "$COMMAND" == "update" ]; then
  echo "Updating uhc..."
  ./scripts/update.sh --force
fi

# Force kill command
if [ "$COMMAND" == "forcekill" ]; then
  echo "Force killing uhc..."
  killall -9 java
  killall -9 screen
fi

# Upload log
if [ "$COMMAND" == "log" ]; then
  echo "Uploading log..."
  cat ./logs/latest.log | nc termbin.com 9999
fi

#!/bin/sh

# Function to update mode-specific files
update_mode_file() {
    local base_path=$1
    local mode=$2
    local target_path=$base_path
    local mode_file_path="${base_path%.*}.$mode.${base_path##*.}"

    if [ -f "$mode_file_path" ]; then
        local mode_data=$(cat "$mode_file_path")
        echo "$mode_data" > "$target_path"
        echo "Updated $(basename $target_path)"
    fi
}

# Mode command
if [ "$COMMAND" = "mode" ]; then
    MODE=$2
    echo "Setting mode to $MODE..."
    FILE_PATH="./plugins/UhcCore/config.$MODE.yml"
    MODE_DATA=$(cat "$FILE_PATH")

    if [ -z "$MODE_DATA" ]; then
        echo "\nMode $MODE does not exist"
        echo "Available modes:"
        ls ./plugins/UhcCore/config.*.yml | xargs -n 1 basename | sed 's/config.//g' | sed 's/.yml//g'
        exit 1
    fi

    echo "$MODE_DATA" > ./plugins/UhcCore/config.yml
    echo "Updated config.yml..."
    echo "$MODE" > ./CURRENT_MODE

    # Update additional mode-specific files
    update_mode_file "./plugins/UhcCore/crafts.yml" "$MODE"
    update_mode_file "./plugins/UhcCore/kits.yml" "$MODE"
    update_mode_file "./plugins/UhcCore/lang.yml" "$MODE"
    update_mode_file "./plugins/UhcCore/scoreboard.yml" "$MODE"
    update_mode_file "./plugins/UhcCore/storage.yml" "$MODE"
    update_mode_file "./plugins/Graves/config/entity.yml" "$MODE"
    # Add other paths as needed
fi
